Traceback (most recent call last):
  File "c:\users\52377\appdata\local\programs\python\python38\lib\site-packages\jupyter_core\utils\__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\52377\appdata\local\programs\python\python38\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "c:\users\52377\appdata\local\programs\python\python38\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\52377\appdata\local\programs\python\python38\lib\site-packages\jupyter_core\utils\__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
  File "c:\users\52377\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\users\52377\appdata\local\programs\python\python38\lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "c:\users\52377\appdata\local\programs\python\python38\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "c:\users\52377\appdata\local\programs\python\python38\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

col_scores = {}
for j, col in enumerate(desc_cols):
    X_tr, X_te = train_test_split(X, test_size=0.25, random_state=42)
    y_tr, y_te = X_tr[:, j].copy(), X_te[:, j].copy()

    X_trm = X_tr.copy(); X_trm[:, j] = np.nan
    X_tem = X_te.copy(); X_tem[:, j] = np.nan

    imp = SimpleImputer(strategy="mean").fit(X_trm)
    X_trf = imp.transform(X_trm)
    X_tef = imp.transform(X_tem)

    X_tr_use = np.delete(X_trf, j, axis=1)
    X_te_use = np.delete(X_tef, j, axis=1)

    reg = LinearRegression().fit(X_tr_use, y_tr)
    y_hat = reg.predict(X_te_use)
    col_scores[col] = r2_score(y_te, y_hat)

pd.Series(col_scores).sort_values(ascending=False).round(3)
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mIndexError[0m                                Traceback (most recent call last)
Cell [1;32mIn[6], line 17[0m
[0;32m     14[0m X_trf [38;5;241m=[39m imp[38;5;241m.[39mtransform(X_trm)
[0;32m     15[0m X_tef [38;5;241m=[39m imp[38;5;241m.[39mtransform(X_tem)
[1;32m---> 17[0m X_tr_use [38;5;241m=[39m [43mnp[49m[38;5;241;43m.[39;49m[43mdelete[49m[43m([49m[43mX_trf[49m[43m,[49m[43m [49m[43mj[49m[43m,[49m[43m [49m[43maxis[49m[38;5;241;43m=[39;49m[38;5;241;43m1[39;49m[43m)[49m
[0;32m     18[0m X_te_use [38;5;241m=[39m np[38;5;241m.[39mdelete(X_tef, j, axis[38;5;241m=[39m[38;5;241m1[39m)
[0;32m     20[0m reg [38;5;241m=[39m LinearRegression()[38;5;241m.[39mfit(X_tr_use, y_tr)

File [1;32m<__array_function__ internals>:200[0m, in [0;36mdelete[1;34m(*args, **kwargs)[0m

File [1;32mc:\users\52377\appdata\local\programs\python\python38\lib\site-packages\numpy\lib\function_base.py:5211[0m, in [0;36mdelete[1;34m(arr, obj, axis)[0m
[0;32m   5208[0m [38;5;28;01mif[39;00m single_value:
[0;32m   5209[0m     [38;5;66;03m# optimization for a single value[39;00m
[0;32m   5210[0m     [38;5;28;01mif[39;00m (obj [38;5;241m<[39m [38;5;241m-[39mN [38;5;129;01mor[39;00m obj [38;5;241m>[39m[38;5;241m=[39m N):
[1;32m-> 5211[0m         [38;5;28;01mraise[39;00m [38;5;167;01mIndexError[39;00m(
[0;32m   5212[0m             [38;5;124m"[39m[38;5;124mindex [39m[38;5;132;01m%i[39;00m[38;5;124m is out of bounds for axis [39m[38;5;132;01m%i[39;00m[38;5;124m with [39m[38;5;124m"[39m
[0;32m   5213[0m             [38;5;124m"[39m[38;5;124msize [39m[38;5;132;01m%i[39;00m[38;5;124m"[39m [38;5;241m%[39m (obj, axis, N))
[0;32m   5214[0m     [38;5;28;01mif[39;00m (obj [38;5;241m<[39m [38;5;241m0[39m):
[0;32m   5215[0m         obj [38;5;241m+[39m[38;5;241m=[39m N

[1;31mIndexError[0m: index 9 is out of bounds for axis 1 with size 9

